name: push2gorouter
description: A command-line tool to automatically assist in migrating from Flutter's Navigator 2.0 to the go_router package.

homepage: https://github.com/Ehsan-abaci
repository: https://github.com/Ehsan-abaci/Push2GoRouter.git

version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  push2gorouter:

dependencies:
  analyzer: ">=6.5.0 <7.4.0"
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  analyzer: ">=6.5.0 <7.4.0"
