name: push2gorouter
description: A command-line tool to automatically assist in migrating from Flutter's Navigator 2.0 to the go_router package.

homepage: https://github.com/Ehsan-abaci
repository: https://github.com/Ehsan-abaci/Push2GoRouter.git

version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  push2gorouter: migrate

dependencies:
  analyzer: ^8.1.1
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
